services:
  images:
    image: ghcr.io/imgproxy/imgproxy:latest
    restart: unless-stopped
    volumes:
      - ./data/imgproxy:/mnt/data
      - ${UPLOAD_PATH}:/mnt/images:ro
    networks:
      - database
    environment:
      PORT: 9000
      IMGPROXY_KEY: "${IMGPROXY_KEY:-imgproxy_key}"
      IMGPROXY_SALT: "${IMGPROXY_SALT:-imgproxy_salt}"
      IMGPROXY_WORKERS: 20
      IMGPROXY_USE_ETAG: "true"
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: "/mnt/images"
    ports:
      - "${IMGPROXY_PORT:-9000}:9000"

  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    networks:
      - database
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: ihunt
    ports:
      - 5555:5432

networks:
  database:
