services:
  images:
    image: ghcr.io/imgproxy/imgproxy:latest
    volumes:
      - ./data/imgproxy:/mnt/data
      - ${MEDIA_PATH}:/mnt/images
    environment:
      PORT: 9000
      IMGPROXY_KEY: ${IMGPROXY_KEY}
      IMGPROXY_SALT: ${IMGPROXY_SALT}
      IMGPROXY_WORKERS: 20
      IMGPROXY_USE_ETAG: "true"
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: "/mnt/images"
    command: -enable-url-source -mount /mnt/data
    ports:
      - "9000:9000"
