services:
  images:
    image: ghcr.io/imgproxy/imgproxy:latest
    restart: unless-stopped
    volumes:
      - ./data/imgproxy:/mnt/data
      - ${MEDIA_PATH}:/mnt/images:ro
    environment:
      PORT: "${IMGPROXY_PORT:-9000}"
      IMGPROXY_KEY: "${IMGPROXY_KEY:-imgproxy_key}"
      IMGPROXY_SALT: "${IMGPROXY_SALT:-imgproxy_salt}"
      IMGPROXY_WORKERS: 20
      IMGPROXY_USE_ETAG: "true"
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: "/mnt/images"
      IMGPROXY_PATH_PREFIX: "${IMGPROXY_PATH:-}"
    ports:
      - "9000:${IMGPROXY_PORT:-9000}"

  static:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./static.conf:/etc/nginx/templates/default.conf.template:ro
      - ./data/cache:/var/cache/nginx:delegated
    links:
      - images:images
    environment:
      IMGPROXY_PORT: "${IMGPROXY_PORT:-9000}"
      IMGPROXY_PATH: "${IMGPROXY_PATH:-}"
    ports:
      - "4444:80"
