name: ihunt-prod
services:
  api:
    build:
      dockerfile: "./config/Dockerfile"
    restart: unless-stopped
    volumes:
      - ./config/data/uploads:/media
      - ./config/data/db:/app/db
    env_file: .env.production
    environment:
      SERVER_HOSTS: https://ihunt.local
      NODE_ENV: production
      DB_PATH: /app/db/prod.db
      UPLOAD_PATH: /media
      MEDIA_HOST: ihunt.local/images

  images:
    image: ghcr.io/imgproxy/imgproxy:latest
    restart: unless-stopped
    volumes:
      - ./config/data/uploads:/mnt/images:ro
    env_file: .env.production
    environment:
      PORT: 9000
      IMGPROXY_WORKERS: 20
      IMGPROXY_USE_ETAG: "true"
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: "/mnt/images"
      IMGPROXY_PATH_PREFIX: /images

  static:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./config/nginx.conf:/etc/nginx/templates/default.conf.template:ro
      - ./dist/client:/etc/nginx/html:ro
      - nginx_cache:/var/cache/nginx:delegated
    links:
      - images:images
      - api:api
    ports:
      - "9999:80"

volumes:
  nginx_cache:
